const icon = {
    logo: require('./logo.svg').default,
    menu: require('./menu.svg').default,
    xmark: require('./xmark.svg').default,
    point: require('./point.svg').default,
    mail: require('./mail.svg').default,
    phone: require('./phone.svg').default,
    facebook: require('./facebook.svg').default,
    time: require('./time.svg').default,
    search: require('./search.svg').default,
    arrow_right: require('./arrow-right.svg').default,
    download: require('./download.svg').default,
    paginate_next: require('./paginate_next.svg').default,
    paginate_prev_disable: require('./paginate_prev_disable.svg').default,
    filter: require('./filter.svg').default,
    prev_next: require('./prev_next.svg').default,
    prev_prev: require('./prev_prev.svg').default,
    logo_mini: require('./logo_mini.svg').default,
    light: require('./light.svg').default,
    news: require('./news.svg').default,
    event: require('./event.svg').default,
    notification: require('./notification.svg').default,
    file: require('./file.svg').default,
    group: require('./group.svg').default,
    sort: require('./sort.svg').default,
    card: require('./card.svg').default,
    bag: require('./bag.svg').default,
    location: require('./location.svg').default,
    location_grey: require('./location_grey.svg').default,
    clock_grey: require('./clock_grey.svg').default,
    damsen_logo: require('./damsen_logo.svg').default,
    calendar: require('./calendar.svg').default
};

export default icon;
